# Generated by Django 5.0.4 on 2024-10-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_bookings_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.driverreg'),
        ),
    ]
