# Generated by Django 5.0.4 on 2024-10-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_bookings_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pickingdate', models.DateField()),
                ('pickingpoint', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('totalprices', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Refund Initiated', 'Refund Initiated')], default='pending', max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(default='Razor_pay', max_length=200, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.driverreg')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.add_service')),
                ('user_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
