# Generated by Django 5.0.4 on 2024-10-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cancelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelbooking',
            name='price',
        ),
    ]
