# Generated by Django 5.0.4 on 2024-10-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_cancelbooking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverreg',
            name='c_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.CreateModel(
            name='cancelsucces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=100)),
                ('pickingdate', models.DateField()),
                ('pickingpoint', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('totalprices', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.driverreg')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.add_service')),
                ('user_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
