# Generated by Django 5.0.4 on 2024-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_driverreg_c_status_cancelsucces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelbooking',
            name='totalprices',
            field=models.IntegerField(),
        ),
    ]
