# Generated by Django 5.0.4 on 2024-10-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_cancelbooking_totalprices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelbooking',
            old_name='status',
            new_name='r_status',
        ),
    ]
