# Generated by Django 5.0.4 on 2024-10-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_status_cancelbooking_r_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelbooking',
            name='refund_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
