# Generated by Django 5.0.4 on 2024-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_cancelbooking_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_location',
            name='district',
            field=models.CharField(default='Ernakulam', max_length=100),
        ),
        migrations.AddField(
            model_name='add_location',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
        ),
    ]
