# Generated by Django 5.0.4 on 2024-10-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_driverreg_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverreg',
            old_name='status',
            new_name='emp_status',
        ),
    ]
