# Generated by Django 5.0.4 on 2024-10-26 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_status_driverreg_emp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='finishedworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=15)),
                ('pickingdate', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('emp_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.driverreg')),
                ('user_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
