# Generated by Django 5.0.4 on 2024-10-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_finishedworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedworks',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
